import { config } from "dotenv";
config({ path: ".env.local" });
config({ path: ".env" });

import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

async function main() {
  // Seed admin user
  const adminEmail = process.env.ADMIN_EMAIL ?? "admin@cypruskeys.com";
  const adminPassword = process.env.ADMIN_PASSWORD ?? "changeme123";
  const passwordHash = await bcrypt.hash(adminPassword, 12);

  await prisma.adminUser.upsert({
    where: { email: adminEmail },
    update: {},
    create: { email: adminEmail, passwordHash },
  });

  console.log(`Admin user seeded: ${adminEmail}`);

  // Clear existing properties
  await prisma.property.deleteMany({});
  console.log("Cleared existing properties");

  // Seed properties with 2K images
  const properties = [
    {
      title: "Panoramic Pool Villa",
      location: "Girne, North Cyprus",
      city: "Girne",
      type: "villa" as const,
      status: "sale" as const,
      priceAmount: 285000,
      currency: "GBP",
      beds: 4,
      baths: 3,
      area: 210,
      photo: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=2560&q=100",
      gallery: [
        "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=2560&q=100",
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=2560&q=100",
        "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=2560&q=100",
        "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=2560&q=100",
      ],
      description:
        "Stunning 4-bedroom villa with infinity pool and panoramic sea-to-mountain views in Girne. Premium materials, private garden and covered parking.",
      features: [
        { label: "Property Type", value: "Villa" },
        { label: "Status", value: "For Sale" },
        { label: "Bedrooms", value: "4" },
        { label: "Bathrooms", value: "3" },
        { label: "Living Area", value: "210 m2" },
        { label: "Plot Size", value: "650 m2" },
        { label: "Year Built", value: "2022" },
        { label: "Title Deed", value: "Turkish Kocan" },
        { label: "Pool", value: "Private Infinity Pool" },
        { label: "Parking", value: "2 Covered Spaces" },
      ],
      yearBuilt: 2022,
      isPublished: true,
    },
    {
      title: "Modern Seafront Residence",
      location: "Iskele, North Cyprus",
      city: "Iskele",
      type: "apartment" as const,
      status: "sale" as const,
      priceAmount: 195000,
      currency: "GBP",
      beds: 3,
      baths: 2,
      area: 130,
      photo: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=2560&q=100",
      gallery: [
        "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=2560&q=100",
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=2560&q=100",
        "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=2560&q=100",
      ],
      description:
        "Stylish 3-bedroom seafront residence in Iskele with direct beach access, modern open-plan living and a large private terrace overlooking the Mediterranean.",
      features: [
        { label: "Property Type", value: "Apartment" },
        { label: "Status", value: "For Sale" },
        { label: "Bedrooms", value: "3" },
        { label: "Bathrooms", value: "2" },
        { label: "Living Area", value: "130 m2" },
        { label: "Terrace", value: "45 m2" },
        { label: "Year Built", value: "2023" },
        { label: "Title Deed", value: "Turkish Kocan" },
        { label: "View", value: "Sea Front" },
        { label: "Parking", value: "1 Space" },
      ],
      yearBuilt: 2023,
      isPublished: true,
    },
    {
      title: "Esentepe Luxury Villa",
      location: "Esentepe, North Cyprus",
      city: "Esentepe",
      type: "villa" as const,
      status: "sale" as const,
      priceAmount: 340000,
      currency: "GBP",
      beds: 4,
      baths: 3,
      area: 195,
      photo: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=2560&q=100",
      gallery: [
        "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=2560&q=100",
        "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=2560&q=100",
        "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=2560&q=100",
      ],
      description:
        "Magnificent 4-bedroom villa set on elevated grounds in Esentepe with stunning golf course and sea views. Private pool, landscaped garden and premium smart-home system.",
      features: [
        { label: "Property Type", value: "Villa" },
        { label: "Status", value: "For Sale" },
        { label: "Bedrooms", value: "4" },
        { label: "Bathrooms", value: "3" },
        { label: "Living Area", value: "195 m2" },
        { label: "Plot Size", value: "580 m2" },
        { label: "Year Built", value: "2023" },
        { label: "Title Deed", value: "Turkish Kocan" },
        { label: "Pool", value: "Private 9x4 m" },
        { label: "Parking", value: "2 Spaces" },
      ],
      yearBuilt: 2023,
      isPublished: true,
    },
    {
      title: "Tatlisu Exclusive Estate",
      location: "Tatlisu, North Cyprus",
      city: "Tatlisu",
      type: "villa" as const,
      status: "sale" as const,
      priceAmount: 475000,
      currency: "GBP",
      beds: 5,
      baths: 4,
      area: 280,
      photo: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=2560&q=100",
      gallery: [
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=2560&q=100",
        "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=2560&q=100",
        "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=2560&q=100",
      ],
      description:
        "An exclusive 5-bedroom estate in Tatlisu with private infinity pool, sea views, a fully equipped outdoor kitchen and 800 m2 of landscaped grounds.",
      features: [
        { label: "Property Type", value: "Villa" },
        { label: "Status", value: "For Sale" },
        { label: "Bedrooms", value: "5" },
        { label: "Bathrooms", value: "4" },
        { label: "Living Area", value: "280 m2" },
        { label: "Plot Size", value: "800 m2" },
        { label: "Year Built", value: "2024" },
        { label: "Title Deed", value: "Turkish Kocan" },
        { label: "Pool", value: "Infinity Pool" },
        { label: "Parking", value: "3 Spaces" },
      ],
      yearBuilt: 2024,
      isPublished: true,
    },
    {
      title: "Girne Harbour Penthouse",
      location: "Girne, North Cyprus",
      city: "Girne",
      type: "penthouse" as const,
      status: "sale" as const,
      priceAmount: 420000,
      currency: "GBP",
      beds: 3,
      baths: 2,
      area: 175,
      photo: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=2560&q=100",
      gallery: [
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=2560&q=100",
        "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=2560&q=100",
      ],
      description:
        "Spectacular rooftop penthouse overlooking Girne harbour with a wrap-around terrace, jacuzzi and panoramic sea views. Fully furnished to the highest standard.",
      features: [
        { label: "Property Type", value: "Penthouse" },
        { label: "Status", value: "For Sale" },
        { label: "Bedrooms", value: "3" },
        { label: "Bathrooms", value: "2" },
        { label: "Living Area", value: "175 m2" },
        { label: "Terrace", value: "90 m2" },
        { label: "Year Built", value: "2023" },
        { label: "Title Deed", value: "Turkish Kocan" },
        { label: "Jacuzzi", value: "Yes" },
        { label: "Parking", value: "2 Spaces" },
      ],
      yearBuilt: 2023,
      floor: 10,
      totalFloors: 10,
      isPublished: true,
    },
    {
      title: "Lapta Hillside Villa",
      location: "Lapta, North Cyprus",
      city: "Lapta",
      type: "villa" as const,
      status: "sale" as const,
      priceAmount: 320000,
      currency: "GBP",
      beds: 3,
      baths: 2,
      area: 175,
      photo: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=2560&q=100",
      gallery: [
        "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=2560&q=100",
        "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=2560&q=100",
      ],
      description:
        "Private hillside villa with a large pool, mountain-to-sea views and mature gardens in peaceful Lapta, 15 minutes from Girne centre.",
      features: [
        { label: "Property Type", value: "Villa" },
        { label: "Status", value: "For Sale" },
        { label: "Bedrooms", value: "3" },
        { label: "Bathrooms", value: "2" },
        { label: "Living Area", value: "175 m2" },
        { label: "Plot Size", value: "500 m2" },
        { label: "Year Built", value: "2021" },
        { label: "Pool", value: "Private 8x4 m" },
        { label: "Title Deed", value: "Turkish Kocan" },
        { label: "Parking", value: "2 Spaces" },
      ],
      yearBuilt: 2021,
      isPublished: true,
    },
    {
      title: "Famagusta Sea View Apartment",
      location: "Famagusta, North Cyprus",
      city: "Famagusta",
      type: "apartment" as const,
      status: "rent" as const,
      priceAmount: 1400,
      currency: "GBP",
      beds: 2,
      baths: 1,
      area: 90,
      photo: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=2560&q=100",
      gallery: [
        "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=2560&q=100",
        "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=2560&q=100",
      ],
      description:
        "Bright 2-bedroom apartment with sea views near the historic Famagusta walls. Fully furnished, air-conditioned, available for annual or seasonal rental.",
      features: [
        { label: "Property Type", value: "Apartment" },
        { label: "Status", value: "For Rent" },
        { label: "Bedrooms", value: "2" },
        { label: "Bathrooms", value: "1" },
        { label: "Living Area", value: "90 m2" },
        { label: "Floor", value: "4th of 7" },
        { label: "Furnished", value: "Yes" },
        { label: "View", value: "Sea View" },
        { label: "Heating", value: "Air Conditioning" },
        { label: "Parking", value: "1 Space" },
      ],
      yearBuilt: 2021,
      floor: 4,
      totalFloors: 7,
      isPublished: true,
    },
    // ── 33 additional mock properties ──
    {
      title: "Alsancak Beach Club Apartment",
      location: "Alsancak, North Cyprus",
      city: "Alsancak",
      type: "apartment" as const,
      status: "sale" as const,
      priceAmount: 145000,
      currency: "GBP",
      beds: 2,
      baths: 1,
      area: 95,
      photo: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=2560&q=100","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=2560&q=100"],
      description: "Modern 2-bed apartment in a popular beach club complex in Alsancak. Communal pool, gym, 24h security and 5 minutes walk from the sea.",
      features: [{ label: "Property Type", value: "Apartment" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "2" },{ label: "Bathrooms", value: "1" },{ label: "Living Area", value: "95 m2" },{ label: "Year Built", value: "2021" },{ label: "Pool", value: "Communal" },{ label: "Parking", value: "1 Space" }],
      yearBuilt: 2021,
      floor: 2,
      totalFloors: 5,
      isPublished: true,
    },
    {
      title: "Kyrenia Old Harbour Penthouse",
      location: "Girne, North Cyprus",
      city: "Girne",
      type: "penthouse" as const,
      status: "sale" as const,
      priceAmount: 390000,
      currency: "GBP",
      beds: 3,
      baths: 2,
      area: 165,
      photo: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=2560&q=100","https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=2560&q=100"],
      description: "Rooftop penthouse above the Kyrenia Old Harbour with wrap-around terrace, jacuzzi and unobstructed sea views. Walking distance to restaurants and marina.",
      features: [{ label: "Property Type", value: "Penthouse" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "3" },{ label: "Bathrooms", value: "2" },{ label: "Living Area", value: "165 m2" },{ label: "Terrace", value: "80 m2" },{ label: "Year Built", value: "2020" },{ label: "Jacuzzi", value: "Yes" }],
      yearBuilt: 2020,
      floor: 8,
      totalFloors: 8,
      isPublished: true,
    },
    {
      title: "Bogaz Waterfront Bungalow",
      location: "Bogaz, North Cyprus",
      city: "Bogaz",
      type: "bungalow" as const,
      status: "sale" as const,
      priceAmount: 210000,
      currency: "GBP",
      beds: 3,
      baths: 2,
      area: 140,
      photo: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=2560&q=100","https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=2560&q=100"],
      description: "Charming waterfront bungalow steps from Bogaz harbour. Open-plan living, private garden with BBQ, and a mooring option available for small boats.",
      features: [{ label: "Property Type", value: "Bungalow" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "3" },{ label: "Bathrooms", value: "2" },{ label: "Living Area", value: "140 m2" },{ label: "Plot Size", value: "350 m2" },{ label: "Year Built", value: "2019" },{ label: "View", value: "Sea Front" }],
      yearBuilt: 2019,
      isPublished: true,
    },
    {
      title: "Ozankoy Countryside Villa",
      location: "Ozankoy, North Cyprus",
      city: "Ozankoy",
      type: "villa" as const,
      status: "sale" as const,
      priceAmount: 265000,
      currency: "GBP",
      beds: 3,
      baths: 2,
      area: 160,
      photo: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=2560&q=100","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=2560&q=100"],
      description: "Peaceful 3-bed villa surrounded by carob and olive trees in the village of Ozankoy. Private pool, stone terrace and mountain views, 10 min from Girne.",
      features: [{ label: "Property Type", value: "Villa" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "3" },{ label: "Bathrooms", value: "2" },{ label: "Living Area", value: "160 m2" },{ label: "Plot Size", value: "450 m2" },{ label: "Year Built", value: "2020" },{ label: "Pool", value: "Private 7x3 m" }],
      yearBuilt: 2020,
      isPublished: true,
    },
    {
      title: "Lefkosa City Centre Studio",
      location: "Lefkosa, North Cyprus",
      city: "Lefkosa",
      type: "apartment" as const,
      status: "rent" as const,
      priceAmount: 700,
      currency: "GBP",
      beds: 1,
      baths: 1,
      area: 55,
      photo: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=2560&q=100"],
      description: "Fully furnished studio apartment in central Lefkosa. Ideal for professionals or students. Walking distance to the UN buffer zone, restaurants and government offices.",
      features: [{ label: "Property Type", value: "Apartment" },{ label: "Status", value: "For Rent" },{ label: "Bedrooms", value: "1" },{ label: "Bathrooms", value: "1" },{ label: "Living Area", value: "55 m2" },{ label: "Floor", value: "3rd of 6" },{ label: "Furnished", value: "Fully" },{ label: "Heating", value: "Central" }],
      yearBuilt: 2018,
      floor: 3,
      totalFloors: 6,
      isPublished: true,
    },
    {
      title: "Catalkoy Sea View Apartment",
      location: "Catalkoy, North Cyprus",
      city: "Catalkoy",
      type: "apartment" as const,
      status: "sale" as const,
      priceAmount: 175000,
      currency: "GBP",
      beds: 2,
      baths: 2,
      area: 110,
      photo: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=2560&q=100","https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=2560&q=100"],
      description: "Spacious 2-bed apartment in Catalkoy with sea views from every room. Communal infinity pool, gym and underground parking included in the price.",
      features: [{ label: "Property Type", value: "Apartment" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "2" },{ label: "Bathrooms", value: "2" },{ label: "Living Area", value: "110 m2" },{ label: "Year Built", value: "2022" },{ label: "Pool", value: "Communal Infinity" },{ label: "Parking", value: "Underground" }],
      yearBuilt: 2022,
      floor: 4,
      totalFloors: 6,
      isPublished: true,
    },
    {
      title: "Girne Modern Investment Apartment",
      location: "Girne, North Cyprus",
      city: "Girne",
      type: "apartment" as const,
      status: "sale" as const,
      priceAmount: 120000,
      currency: "GBP",
      beds: 1,
      baths: 1,
      area: 70,
      photo: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=2560&q=100","https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=2560&q=100"],
      description: "High-yield 1-bed investment apartment in a managed complex near Girne town centre. Rental management available with projected 7–8% annual yield.",
      features: [{ label: "Property Type", value: "Apartment" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "1" },{ label: "Bathrooms", value: "1" },{ label: "Living Area", value: "70 m2" },{ label: "Year Built", value: "2023" },{ label: "Rental Yield", value: "7–8% est." },{ label: "Furnished", value: "Fully" }],
      yearBuilt: 2023,
      floor: 1,
      totalFloors: 4,
      isPublished: true,
    },
    {
      title: "Karpaz Peninsula Eco-Villa",
      location: "Karpaz, North Cyprus",
      city: "Karpaz",
      type: "villa" as const,
      status: "sale" as const,
      priceAmount: 520000,
      currency: "GBP",
      beds: 4,
      baths: 3,
      area: 240,
      photo: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=2560&q=100","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=2560&q=100"],
      description: "Unique eco-villa on the untouched Karpaz Peninsula with solar panels, rainwater harvesting and direct access to a private sandy beach. A rare opportunity.",
      features: [{ label: "Property Type", value: "Villa" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "4" },{ label: "Bathrooms", value: "3" },{ label: "Living Area", value: "240 m2" },{ label: "Plot Size", value: "1200 m2" },{ label: "Year Built", value: "2021" },{ label: "Solar Panels", value: "Yes" }],
      yearBuilt: 2021,
      isPublished: true,
    },
    {
      title: "Iskele Long Beach Studio",
      location: "Iskele, North Cyprus",
      city: "Iskele",
      type: "apartment" as const,
      status: "rent" as const,
      priceAmount: 900,
      currency: "GBP",
      beds: 1,
      baths: 1,
      area: 58,
      photo: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=2560&q=100"],
      description: "Well-maintained studio in Long Beach complex, Iskele. Private beach, 3 pools, restaurants and sports facilities on-site. Perfect for seasonal or annual rental.",
      features: [{ label: "Property Type", value: "Apartment" },{ label: "Status", value: "For Rent" },{ label: "Bedrooms", value: "1" },{ label: "Bathrooms", value: "1" },{ label: "Living Area", value: "58 m2" },{ label: "Floor", value: "2nd of 8" },{ label: "Furnished", value: "Fully" },{ label: "Beach", value: "Private Beach Access" }],
      yearBuilt: 2022,
      floor: 2,
      totalFloors: 8,
      isPublished: true,
    },
    {
      title: "Esentepe Golf Community Bungalow",
      location: "Esentepe, North Cyprus",
      city: "Esentepe",
      type: "bungalow" as const,
      status: "sale" as const,
      priceAmount: 230000,
      currency: "GBP",
      beds: 2,
      baths: 2,
      area: 120,
      photo: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=2560&q=100","https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=2560&q=100"],
      description: "Charming 2-bed bungalow within the Esentepe golf community. Mountain and fairway views, communal pool and clubhouse membership included.",
      features: [{ label: "Property Type", value: "Bungalow" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "2" },{ label: "Bathrooms", value: "2" },{ label: "Living Area", value: "120 m2" },{ label: "Year Built", value: "2020" },{ label: "Golf", value: "Community Course" },{ label: "Pool", value: "Communal" }],
      yearBuilt: 2020,
      isPublished: true,
    },
    {
      title: "Lapta Sea View Penthouse",
      location: "Lapta, North Cyprus",
      city: "Lapta",
      type: "penthouse" as const,
      status: "sale" as const,
      priceAmount: 295000,
      currency: "GBP",
      beds: 3,
      baths: 2,
      area: 155,
      photo: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=2560&q=100","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=2560&q=100"],
      description: "Top-floor penthouse in Lapta with sweeping sea and mountain views from a 60 m2 wrap-around terrace. Private jacuzzi, 2 parking spaces and storage room.",
      features: [{ label: "Property Type", value: "Penthouse" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "3" },{ label: "Bathrooms", value: "2" },{ label: "Living Area", value: "155 m2" },{ label: "Terrace", value: "60 m2" },{ label: "Year Built", value: "2022" },{ label: "Jacuzzi", value: "Yes" }],
      yearBuilt: 2022,
      floor: 7,
      totalFloors: 7,
      isPublished: true,
    },
    {
      title: "Girne Commercial Office Space",
      location: "Girne, North Cyprus",
      city: "Girne",
      type: "commercial" as const,
      status: "rent" as const,
      priceAmount: 2200,
      currency: "GBP",
      beds: 0,
      baths: 2,
      area: 200,
      photo: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=2560&q=100"],
      description: "Prime commercial office space on the main boulevard in Girne. Open-plan layout, 2 meeting rooms, kitchenette and 4 parking spaces. Ideal for financial or legal firms.",
      features: [{ label: "Property Type", value: "Commercial" },{ label: "Status", value: "For Rent" },{ label: "Total Area", value: "200 m2" },{ label: "Floor", value: "Ground" },{ label: "Parking", value: "4 Spaces" },{ label: "Year Built", value: "2018" },{ label: "Air Conditioning", value: "Yes" },{ label: "Internet", value: "Fibre Ready" }],
      yearBuilt: 2018,
      floor: 0,
      totalFloors: 4,
      isPublished: true,
    },
    {
      title: "Tatlisu Hillside Retreat",
      location: "Tatlisu, North Cyprus",
      city: "Tatlisu",
      type: "villa" as const,
      status: "sale" as const,
      priceAmount: 310000,
      currency: "GBP",
      beds: 3,
      baths: 2,
      area: 168,
      photo: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=2560&q=100","https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=2560&q=100"],
      description: "Serene hillside villa in Tatlisu with private pool, olive grove and Mediterranean sea views. 3 bedrooms, open living, covered terrace and spacious garden.",
      features: [{ label: "Property Type", value: "Villa" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "3" },{ label: "Bathrooms", value: "2" },{ label: "Living Area", value: "168 m2" },{ label: "Plot Size", value: "600 m2" },{ label: "Year Built", value: "2021" },{ label: "Pool", value: "Private 8x4 m" }],
      yearBuilt: 2021,
      isPublished: true,
    },
    {
      title: "Alsancak Luxury Penthouse",
      location: "Alsancak, North Cyprus",
      city: "Alsancak",
      type: "penthouse" as const,
      status: "sale" as const,
      priceAmount: 420000,
      currency: "GBP",
      beds: 4,
      baths: 3,
      area: 200,
      photo: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=2560&q=100","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=2560&q=100"],
      description: "Spectacular 4-bed penthouse in Alsancak with private rooftop pool, bar area and panoramic sea views. Smart home system, cinema room and premium finishes throughout.",
      features: [{ label: "Property Type", value: "Penthouse" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "4" },{ label: "Bathrooms", value: "3" },{ label: "Living Area", value: "200 m2" },{ label: "Roof Terrace", value: "90 m2" },{ label: "Year Built", value: "2023" },{ label: "Pool", value: "Rooftop Private" }],
      yearBuilt: 2023,
      floor: 9,
      totalFloors: 9,
      isPublished: true,
    },
    {
      title: "Bogaz Investment Apartment",
      location: "Bogaz, North Cyprus",
      city: "Bogaz",
      type: "apartment" as const,
      status: "sale" as const,
      priceAmount: 165000,
      currency: "GBP",
      beds: 2,
      baths: 2,
      area: 105,
      photo: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=2560&q=100"],
      description: "Harbour-view 2-bed apartment in Bogaz with sea-facing balcony, communal pool and integrated rental programme. Ideal for buy-to-let investors.",
      features: [{ label: "Property Type", value: "Apartment" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "2" },{ label: "Bathrooms", value: "2" },{ label: "Living Area", value: "105 m2" },{ label: "Year Built", value: "2022" },{ label: "Rental Yield", value: "6–7% est." },{ label: "View", value: "Harbour" }],
      yearBuilt: 2022,
      floor: 3,
      totalFloors: 6,
      isPublished: true,
    },
    {
      title: "Girne Seafront Rental Apartment",
      location: "Girne, North Cyprus",
      city: "Girne",
      type: "apartment" as const,
      status: "rent" as const,
      priceAmount: 1600,
      currency: "GBP",
      beds: 2,
      baths: 1,
      area: 100,
      photo: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=2560&q=100","https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=2560&q=100"],
      description: "Stylishly furnished 2-bedroom apartment with direct sea views in central Girne. Available furnished for annual rental. Pool access and beach club membership included.",
      features: [{ label: "Property Type", value: "Apartment" },{ label: "Status", value: "For Rent" },{ label: "Bedrooms", value: "2" },{ label: "Bathrooms", value: "1" },{ label: "Living Area", value: "100 m2" },{ label: "Furnished", value: "Yes" },{ label: "View", value: "Sea Front" },{ label: "Pool", value: "Communal" }],
      yearBuilt: 2020,
      floor: 5,
      totalFloors: 8,
      isPublished: true,
    },
    {
      title: "Lefkosa Business District Commercial",
      location: "Lefkosa, North Cyprus",
      city: "Lefkosa",
      type: "commercial" as const,
      status: "sale" as const,
      priceAmount: 380000,
      currency: "GBP",
      beds: 0,
      baths: 3,
      area: 350,
      photo: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=2560&q=100"],
      description: "Multi-floor commercial building in Lefkosa's central business district. Currently tenanted at 8% yield. Ground-floor retail, 2 upper floors of office space, 10 parking.",
      features: [{ label: "Property Type", value: "Commercial" },{ label: "Status", value: "For Sale" },{ label: "Total Area", value: "350 m2" },{ label: "Floors", value: "3" },{ label: "Parking", value: "10 Spaces" },{ label: "Year Built", value: "2016" },{ label: "Current Yield", value: "8%" },{ label: "Tenancy", value: "Tenanted" }],
      yearBuilt: 2016,
      isPublished: true,
    },
    {
      title: "Catalkoy 5-Bed Family Villa",
      location: "Catalkoy, North Cyprus",
      city: "Catalkoy",
      type: "villa" as const,
      status: "sale" as const,
      priceAmount: 560000,
      currency: "GBP",
      beds: 5,
      baths: 4,
      area: 300,
      photo: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=2560&q=100","https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=2560&q=100"],
      description: "Grand family villa in Catalkoy with 5 en-suite bedrooms, home cinema, gym, infinity pool and 900 m2 landscaped grounds. Gated community with 24h security.",
      features: [{ label: "Property Type", value: "Villa" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "5" },{ label: "Bathrooms", value: "4" },{ label: "Living Area", value: "300 m2" },{ label: "Plot Size", value: "900 m2" },{ label: "Year Built", value: "2022" },{ label: "Pool", value: "Private Infinity" }],
      yearBuilt: 2022,
      isPublished: true,
    },
    {
      title: "Ozankoy Rental Bungalow",
      location: "Ozankoy, North Cyprus",
      city: "Ozankoy",
      type: "bungalow" as const,
      status: "rent" as const,
      priceAmount: 1100,
      currency: "GBP",
      beds: 2,
      baths: 1,
      area: 95,
      photo: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=2560&q=100"],
      description: "Cosy 2-bed bungalow in Ozankoy village available for annual rental. Private garden, BBQ area and mountain views. Quiet neighbourhood, 10 min from Girne.",
      features: [{ label: "Property Type", value: "Bungalow" },{ label: "Status", value: "For Rent" },{ label: "Bedrooms", value: "2" },{ label: "Bathrooms", value: "1" },{ label: "Living Area", value: "95 m2" },{ label: "Garden", value: "Private" },{ label: "Furnished", value: "Part Furnished" },{ label: "Pets", value: "Allowed" }],
      yearBuilt: 2017,
      isPublished: true,
    },
    {
      title: "Karpaz Beachfront Villa",
      location: "Karpaz, North Cyprus",
      city: "Karpaz",
      type: "villa" as const,
      status: "sale" as const,
      priceAmount: 680000,
      currency: "GBP",
      beds: 5,
      baths: 4,
      area: 310,
      photo: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=2560&q=100","https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=2560&q=100"],
      description: "Secluded beachfront villa on the Karpaz Peninsula with private stretch of sandy beach, pool, 5 bedrooms and 1200 m2 grounds. Off-grid solar + battery system installed.",
      features: [{ label: "Property Type", value: "Villa" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "5" },{ label: "Bathrooms", value: "4" },{ label: "Living Area", value: "310 m2" },{ label: "Plot Size", value: "1200 m2" },{ label: "Year Built", value: "2020" },{ label: "Beach", value: "Private" }],
      yearBuilt: 2020,
      isPublished: true,
    },
    {
      title: "Iskele 3-Bed Sea View Apartment",
      location: "Iskele, North Cyprus",
      city: "Iskele",
      type: "apartment" as const,
      status: "sale" as const,
      priceAmount: 215000,
      currency: "GBP",
      beds: 3,
      baths: 2,
      area: 135,
      photo: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=2560&q=100","https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=2560&q=100"],
      description: "Light-filled 3-bed apartment in a boutique development in Iskele. Sea view from living room and master bedroom, communal pool and direct beach access.",
      features: [{ label: "Property Type", value: "Apartment" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "3" },{ label: "Bathrooms", value: "2" },{ label: "Living Area", value: "135 m2" },{ label: "Year Built", value: "2023" },{ label: "Beach", value: "Direct Access" },{ label: "Pool", value: "Communal" }],
      yearBuilt: 2023,
      floor: 3,
      totalFloors: 5,
      isPublished: true,
    },
    {
      title: "Girne Luxury Duplex",
      location: "Girne, North Cyprus",
      city: "Girne",
      type: "apartment" as const,
      status: "sale" as const,
      priceAmount: 335000,
      currency: "GBP",
      beds: 3,
      baths: 3,
      area: 180,
      photo: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=2560&q=100","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=2560&q=100"],
      description: "Two-floor luxury duplex apartment in central Girne with private terrace, sea views and premium appliances throughout. Walking distance to the marina and harbour.",
      features: [{ label: "Property Type", value: "Apartment" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "3" },{ label: "Bathrooms", value: "3" },{ label: "Living Area", value: "180 m2" },{ label: "Terrace", value: "50 m2" },{ label: "Year Built", value: "2022" },{ label: "View", value: "Sea & Marina" }],
      yearBuilt: 2022,
      floor: 6,
      totalFloors: 7,
      isPublished: true,
    },
    {
      title: "Esentepe Rental Villa",
      location: "Esentepe, North Cyprus",
      city: "Esentepe",
      type: "villa" as const,
      status: "rent" as const,
      priceAmount: 2500,
      currency: "GBP",
      beds: 4,
      baths: 3,
      area: 200,
      photo: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=2560&q=100","https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=2560&q=100"],
      description: "Fully furnished 4-bed villa in Esentepe available for long-term rental. Private pool, private gym, golf course views and management service included.",
      features: [{ label: "Property Type", value: "Villa" },{ label: "Status", value: "For Rent" },{ label: "Bedrooms", value: "4" },{ label: "Bathrooms", value: "3" },{ label: "Living Area", value: "200 m2" },{ label: "Pool", value: "Private" },{ label: "Gym", value: "Private" },{ label: "Furnished", value: "Fully" }],
      yearBuilt: 2021,
      isPublished: true,
    },
    {
      title: "Famagusta Historic Quarter Apartment",
      location: "Famagusta, North Cyprus",
      city: "Famagusta",
      type: "apartment" as const,
      status: "sale" as const,
      priceAmount: 155000,
      currency: "GBP",
      beds: 2,
      baths: 1,
      area: 98,
      photo: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=2560&q=100"],
      description: "Charming 2-bed apartment near the historic walls of Famagusta. Modern renovation preserving original stone, sea views from the top floor and balcony.",
      features: [{ label: "Property Type", value: "Apartment" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "2" },{ label: "Bathrooms", value: "1" },{ label: "Living Area", value: "98 m2" },{ label: "Year Built", value: "2019" },{ label: "View", value: "Sea & Historic Walls" },{ label: "Floor", value: "5th" }],
      yearBuilt: 2019,
      floor: 5,
      totalFloors: 6,
      isPublished: true,
    },
    {
      title: "Lapta Pool Bungalow",
      location: "Lapta, North Cyprus",
      city: "Lapta",
      type: "bungalow" as const,
      status: "sale" as const,
      priceAmount: 248000,
      currency: "GBP",
      beds: 3,
      baths: 2,
      area: 130,
      photo: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=2560&q=100","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=2560&q=100"],
      description: "Single-storey 3-bed bungalow with private pool in a quiet part of Lapta. Open-plan kitchen-diner, covered terrace, mature garden. Move-in ready.",
      features: [{ label: "Property Type", value: "Bungalow" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "3" },{ label: "Bathrooms", value: "2" },{ label: "Living Area", value: "130 m2" },{ label: "Plot Size", value: "400 m2" },{ label: "Year Built", value: "2020" },{ label: "Pool", value: "Private 7x3 m" }],
      yearBuilt: 2020,
      isPublished: true,
    },
    {
      title: "Girne Marina Commercial Unit",
      location: "Girne, North Cyprus",
      city: "Girne",
      type: "commercial" as const,
      status: "rent" as const,
      priceAmount: 3500,
      currency: "GBP",
      beds: 0,
      baths: 1,
      area: 120,
      photo: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=2560&q=100"],
      description: "Ground-floor commercial unit with marina views in Girne. Former restaurant space with extraction ducting, 3-phase power and high foot traffic location.",
      features: [{ label: "Property Type", value: "Commercial" },{ label: "Status", value: "For Rent" },{ label: "Total Area", value: "120 m2" },{ label: "Floor", value: "Ground" },{ label: "Year Built", value: "2015" },{ label: "Air Conditioning", value: "Yes" },{ label: "3-Phase Power", value: "Yes" },{ label: "View", value: "Marina" }],
      yearBuilt: 2015,
      floor: 0,
      totalFloors: 6,
      isPublished: true,
    },
    {
      title: "Ozankoy Renovated Stone House",
      location: "Ozankoy, North Cyprus",
      city: "Ozankoy",
      type: "villa" as const,
      status: "sale" as const,
      priceAmount: 185000,
      currency: "GBP",
      beds: 2,
      baths: 1,
      area: 110,
      photo: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=2560&q=100"],
      description: "Beautifully renovated traditional stone house in Ozankoy village. Exposed stone walls, vaulted ceilings, private courtyard with fig tree and mountain views.",
      features: [{ label: "Property Type", value: "Villa" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "2" },{ label: "Bathrooms", value: "1" },{ label: "Living Area", value: "110 m2" },{ label: "Plot Size", value: "280 m2" },{ label: "Year Built", value: "1970" },{ label: "Renovated", value: "2022" }],
      yearBuilt: 1970,
      isPublished: true,
    },
    {
      title: "Tatlisu Sunset Apartment",
      location: "Tatlisu, North Cyprus",
      city: "Tatlisu",
      type: "apartment" as const,
      status: "sale" as const,
      priceAmount: 198000,
      currency: "GBP",
      beds: 2,
      baths: 2,
      area: 115,
      photo: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=2560&q=100","https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=2560&q=100"],
      description: "West-facing 2-bed apartment in Tatlisu with stunning sunset views over the Mediterranean. Communal infinity pool, gym and concierge service in a 5-star complex.",
      features: [{ label: "Property Type", value: "Apartment" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "2" },{ label: "Bathrooms", value: "2" },{ label: "Living Area", value: "115 m2" },{ label: "Year Built", value: "2023" },{ label: "Pool", value: "Communal Infinity" },{ label: "View", value: "Sea Sunset" }],
      yearBuilt: 2023,
      floor: 4,
      totalFloors: 6,
      isPublished: true,
    },
    {
      title: "Alsancak Detached Family Villa",
      location: "Alsancak, North Cyprus",
      city: "Alsancak",
      type: "villa" as const,
      status: "sale" as const,
      priceAmount: 299000,
      currency: "GBP",
      beds: 4,
      baths: 3,
      area: 200,
      photo: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=2560&q=100","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=2560&q=100"],
      description: "Detached 4-bed family villa in Alsancak with private pool, double garage and 600 m2 garden. European-style kitchen, underfloor heating and solar panels.",
      features: [{ label: "Property Type", value: "Villa" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "4" },{ label: "Bathrooms", value: "3" },{ label: "Living Area", value: "200 m2" },{ label: "Plot Size", value: "600 m2" },{ label: "Year Built", value: "2021" },{ label: "Pool", value: "Private" }],
      yearBuilt: 2021,
      isPublished: true,
    },
    {
      title: "Catalkoy Rent-to-Own Apartment",
      location: "Catalkoy, North Cyprus",
      city: "Catalkoy",
      type: "apartment" as const,
      status: "rent" as const,
      priceAmount: 1250,
      currency: "GBP",
      beds: 2,
      baths: 1,
      area: 95,
      photo: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=2560&q=100"],
      description: "Modern 2-bed apartment in Catalkoy available for rent. Fully furnished, sea view balcony, communal pool, gym, 24h security and underground parking.",
      features: [{ label: "Property Type", value: "Apartment" },{ label: "Status", value: "For Rent" },{ label: "Bedrooms", value: "2" },{ label: "Bathrooms", value: "1" },{ label: "Living Area", value: "95 m2" },{ label: "Furnished", value: "Fully" },{ label: "Pool", value: "Communal" },{ label: "View", value: "Sea View" }],
      yearBuilt: 2022,
      floor: 2,
      totalFloors: 5,
      isPublished: true,
    },
    {
      title: "Girne 2+1 New Build Apartment",
      location: "Girne, North Cyprus",
      city: "Girne",
      type: "apartment" as const,
      status: "sale" as const,
      priceAmount: 135000,
      currency: "GBP",
      beds: 2,
      baths: 1,
      area: 85,
      photo: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=2560&q=100","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=2560&q=100"],
      description: "Off-plan 2-bed apartment in a new development near Girne centre. Completion Q3 2025. Flexible payment plan with 30% deposit and 0% interest installments.",
      features: [{ label: "Property Type", value: "Apartment" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "2" },{ label: "Bathrooms", value: "1" },{ label: "Living Area", value: "85 m2" },{ label: "Year Built", value: "2025" },{ label: "Payment Plan", value: "30/70 interest-free" },{ label: "Pool", value: "Communal" }],
      yearBuilt: 2025,
      floor: 2,
      totalFloors: 4,
      isPublished: true,
    },
    {
      title: "Famagusta 3-Bed Rental Villa",
      location: "Famagusta, North Cyprus",
      city: "Famagusta",
      type: "villa" as const,
      status: "rent" as const,
      priceAmount: 1800,
      currency: "GBP",
      beds: 3,
      baths: 2,
      area: 160,
      photo: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=2560&q=100","https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=2560&q=100"],
      description: "Spacious 3-bed villa for rent near Famagusta with private pool, garden, outdoor dining and 2 parking spaces. Available furnished, all utilities included.",
      features: [{ label: "Property Type", value: "Villa" },{ label: "Status", value: "For Rent" },{ label: "Bedrooms", value: "3" },{ label: "Bathrooms", value: "2" },{ label: "Living Area", value: "160 m2" },{ label: "Pool", value: "Private" },{ label: "Utilities", value: "Included" },{ label: "Furnished", value: "Yes" }],
      yearBuilt: 2020,
      isPublished: true,
    },
    {
      title: "Bogaz Seafront Penthouse",
      location: "Bogaz, North Cyprus",
      city: "Bogaz",
      type: "penthouse" as const,
      status: "sale" as const,
      priceAmount: 355000,
      currency: "GBP",
      beds: 3,
      baths: 2,
      area: 170,
      photo: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=2560&q=100","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=2560&q=100"],
      description: "Top-floor penthouse in Bogaz overlooking the fishing harbour. 3 beds, 2 baths, private rooftop terrace with jacuzzi and 360-degree sea views. Rare find.",
      features: [{ label: "Property Type", value: "Penthouse" },{ label: "Status", value: "For Sale" },{ label: "Bedrooms", value: "3" },{ label: "Bathrooms", value: "2" },{ label: "Living Area", value: "170 m2" },{ label: "Roof Terrace", value: "70 m2" },{ label: "Year Built", value: "2021" },{ label: "Jacuzzi", value: "Yes" }],
      yearBuilt: 2021,
      floor: 8,
      totalFloors: 8,
      isPublished: true,
    },
    {
      title: "Iskele Rental Villa with Pool",
      location: "Iskele, North Cyprus",
      city: "Iskele",
      type: "villa" as const,
      status: "rent" as const,
      priceAmount: 2100,
      currency: "GBP",
      beds: 3,
      baths: 2,
      area: 170,
      photo: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=2560&q=100",
      gallery: ["https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=2560&q=100","https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=2560&q=100"],
      description: "Stunning 3-bed villa in Iskele with private pool, sea views and modern design. Available for long-term rental. Minutes from Long Beach and local amenities.",
      features: [{ label: "Property Type", value: "Villa" },{ label: "Status", value: "For Rent" },{ label: "Bedrooms", value: "3" },{ label: "Bathrooms", value: "2" },{ label: "Living Area", value: "170 m2" },{ label: "Pool", value: "Private" },{ label: "View", value: "Sea View" },{ label: "Furnished", value: "Fully" }],
      yearBuilt: 2022,
      isPublished: true,
    },
  ];

  for (const property of properties) {
    await prisma.property.create({ data: property });
  }

  console.log(`Seeded ${properties.length} properties`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
