import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";
import { config } from "dotenv";

config({ path: ".env.local" });

const connectionString = process.env.DATABASE_URL!;
const pool = new pg.Pool({ connectionString });
const adapter = new PrismaPg(pool);
const db = new PrismaClient({ adapter });

const DUBAI_PROPERTIES = [
  // ── FOR SALE (10) ──────────────────────────────────────────────
  {
    title: "Dubai Marina 3-Bed Luxury Apartment",
    location: "Dubai Marina, Dubai",
    city: "Dubai Marina",
    region: "dubai",
    type: "apartment" as const,
    status: "sale" as const,
    priceAmount: 2400000,
    currency: "AED",
    beds: 3,
    baths: 2,
    area: 162,
    photo: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=2560&q=100",
    gallery: [],
    description: "Stunning 3-bedroom apartment in the heart of Dubai Marina with panoramic sea views, modern kitchen, floor-to-ceiling windows and access to rooftop pool. Minutes from JBR Beach.",
    features: [{ label: "View", value: "Sea & Marina" }, { label: "Parking", value: "2 spaces" }, { label: "Gym", value: "Shared" }],
    yearBuilt: 2021,
    floor: 24,
    totalFloors: 42,
    isPublished: true,
  },
  {
    title: "Palm Jumeirah 4-Bed Signature Villa",
    location: "Palm Jumeirah, Dubai",
    city: "Palm Jumeirah",
    region: "dubai",
    type: "villa" as const,
    status: "sale" as const,
    priceAmount: 8500000,
    currency: "AED",
    beds: 4,
    baths: 5,
    area: 510,
    photo: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=2560&q=100",
    gallery: [],
    description: "Exquisite 4-bedroom signature villa on the iconic Palm Jumeirah. Private pool, direct beach access, landscaped garden, and breathtaking views of the Dubai skyline and Arabian Gulf.",
    features: [{ label: "Pool", value: "Private" }, { label: "Beach Access", value: "Direct" }, { label: "Garage", value: "3 cars" }],
    yearBuilt: 2019,
    floor: null,
    totalFloors: null,
    isPublished: true,
  },
  {
    title: "Downtown Dubai 2-Bed Apartment Near Burj Khalifa",
    location: "Downtown Dubai, Dubai",
    city: "Downtown Dubai",
    region: "dubai",
    type: "apartment" as const,
    status: "sale" as const,
    priceAmount: 3200000,
    currency: "AED",
    beds: 2,
    baths: 2,
    area: 118,
    photo: "https://images.unsplash.com/photo-1577415124269-fc1140a69e91?w=2560&q=100",
    gallery: [],
    description: "Elegant 2-bedroom apartment in Downtown Dubai with partial Burj Khalifa and Dubai Fountain views. Open-plan living, premium finishes, and direct access to Dubai Mall.",
    features: [{ label: "View", value: "Burj Khalifa" }, { label: "Parking", value: "1 space" }, { label: "Concierge", value: "24/7" }],
    yearBuilt: 2020,
    floor: 18,
    totalFloors: 35,
    isPublished: true,
  },
  {
    title: "Dubai Hills 5-Bed Golf Course Villa",
    location: "Dubai Hills Estate, Dubai",
    city: "Dubai Hills",
    region: "dubai",
    type: "villa" as const,
    status: "sale" as const,
    priceAmount: 12000000,
    currency: "AED",
    beds: 5,
    baths: 6,
    area: 650,
    photo: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=2560&q=100",
    gallery: [],
    description: "Grand 5-bedroom villa overlooking the Dubai Hills Golf Club. Featuring a private pool, maid's room, landscaped garden, open-plan living areas and a dedicated home cinema room.",
    features: [{ label: "Golf View", value: "Yes" }, { label: "Pool", value: "Private" }, { label: "Cinema", value: "Home cinema" }],
    yearBuilt: 2022,
    floor: null,
    totalFloors: null,
    isPublished: true,
  },
  {
    title: "JBR 1-Bed Beachfront Studio",
    location: "Jumeirah Beach Residence, Dubai",
    city: "JBR",
    region: "dubai",
    type: "apartment" as const,
    status: "sale" as const,
    priceAmount: 950000,
    currency: "AED",
    beds: 1,
    baths: 1,
    area: 65,
    photo: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=2560&q=100",
    gallery: [],
    description: "Chic 1-bedroom apartment steps from JBR Beach. Fully furnished with modern appliances, beach access, and stunning sea views. Ideal for own use or as a short-term rental investment.",
    features: [{ label: "Beach Access", value: "50m" }, { label: "Furnished", value: "Fully" }, { label: "View", value: "Sea view" }],
    yearBuilt: 2018,
    floor: 9,
    totalFloors: 28,
    isPublished: true,
  },
  {
    title: "Business Bay 3-Bed Penthouse with Canal View",
    location: "Business Bay, Dubai",
    city: "Business Bay",
    region: "dubai",
    type: "penthouse" as const,
    status: "sale" as const,
    priceAmount: 5800000,
    currency: "AED",
    beds: 3,
    baths: 3,
    area: 285,
    photo: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=2560&q=100",
    gallery: [],
    description: "Spectacular penthouse in Business Bay with sweeping views of the Dubai Canal and city skyline. Private terrace, chef's kitchen, smart home system, and 2 dedicated parking spaces.",
    features: [{ label: "Canal View", value: "Yes" }, { label: "Terrace", value: "Private 90m²" }, { label: "Smart Home", value: "Full system" }],
    yearBuilt: 2023,
    floor: 42,
    totalFloors: 42,
    isPublished: true,
  },
  {
    title: "Arabian Ranches 4-Bed Townhouse",
    location: "Arabian Ranches, Dubai",
    city: "Arabian Ranches",
    region: "dubai",
    type: "villa" as const,
    status: "sale" as const,
    priceAmount: 4200000,
    currency: "AED",
    beds: 4,
    baths: 4,
    area: 310,
    photo: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=2560&q=100",
    gallery: [],
    description: "Spacious 4-bedroom townhouse in the family-friendly Arabian Ranches community. Private garden, community pool, kids' play area, and easy access to schools and golf courses.",
    features: [{ label: "Garden", value: "Private" }, { label: "Community Pool", value: "Yes" }, { label: "School Nearby", value: "800m" }],
    yearBuilt: 2017,
    floor: null,
    totalFloors: 2,
    isPublished: true,
  },
  {
    title: "DIFC 2-Bed Premium Apartment",
    location: "DIFC, Dubai",
    city: "DIFC",
    region: "dubai",
    type: "apartment" as const,
    status: "sale" as const,
    priceAmount: 2800000,
    currency: "AED",
    beds: 2,
    baths: 2,
    area: 130,
    photo: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=2560&q=100",
    gallery: [],
    description: "Premium 2-bedroom apartment in the financial district of DIFC. Floor-to-ceiling glazing, high-end finishes, access to world-class dining and retail. Strong investment yield.",
    features: [{ label: "Rental Yield", value: "~6.5%" }, { label: "Concierge", value: "24/7" }, { label: "Metro", value: "5 min walk" }],
    yearBuilt: 2021,
    floor: 15,
    totalFloors: 30,
    isPublished: true,
  },
  {
    title: "Jumeirah 6-Bed Beachside Mega Villa",
    location: "Jumeirah, Dubai",
    city: "Jumeirah",
    region: "dubai",
    type: "villa" as const,
    status: "sale" as const,
    priceAmount: 15000000,
    currency: "AED",
    beds: 6,
    baths: 7,
    area: 920,
    photo: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=2560&q=100",
    gallery: [],
    description: "Ultra-luxury 6-bedroom villa in prestigious Jumeirah with private beach access and direct views of the Palm. Featuring two pools, gym, staff quarters, majlis and a rooftop lounge.",
    features: [{ label: "Beach Access", value: "Private" }, { label: "Pools", value: "2 private" }, { label: "Staff Quarters", value: "Yes" }],
    yearBuilt: 2020,
    floor: null,
    totalFloors: 3,
    isPublished: true,
  },
  {
    title: "Dubai South 2-Bed Apartment Near Expo City",
    location: "Dubai South, Dubai",
    city: "Dubai South",
    region: "dubai",
    type: "apartment" as const,
    status: "sale" as const,
    priceAmount: 1100000,
    currency: "AED",
    beds: 2,
    baths: 1,
    area: 92,
    photo: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=2560&q=100",
    gallery: [],
    description: "Modern 2-bedroom apartment near Expo City Dubai and Al Maktoum International Airport. Strong rental demand driven by the growing business hub. Ideal buy-to-let investment.",
    features: [{ label: "Airport", value: "10 min" }, { label: "Expo City", value: "5 min" }, { label: "Yield", value: "~7%" }],
    yearBuilt: 2023,
    floor: 6,
    totalFloors: 18,
    isPublished: true,
  },

  // ── FOR RENT (5) ───────────────────────────────────────────────
  {
    title: "Dubai Marina 2-Bed Furnished Apartment",
    location: "Dubai Marina, Dubai",
    city: "Dubai Marina",
    region: "dubai",
    type: "apartment" as const,
    status: "rent" as const,
    priceAmount: 12000,
    currency: "AED",
    beds: 2,
    baths: 2,
    area: 115,
    photo: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=2560&q=100",
    gallery: [],
    description: "Fully furnished 2-bedroom apartment in Dubai Marina Walk. Modern kitchen, balcony with marina views, gym and pool included. Available for annual lease.",
    features: [{ label: "Furnished", value: "Fully" }, { label: "Marina View", value: "Yes" }, { label: "Bills", value: "Chiller-free" }],
    yearBuilt: 2019,
    floor: 14,
    totalFloors: 36,
    isPublished: true,
  },
  {
    title: "Jumeirah 3-Bed Villa with Private Pool",
    location: "Jumeirah 1, Dubai",
    city: "Jumeirah",
    region: "dubai",
    type: "villa" as const,
    status: "rent" as const,
    priceAmount: 22000,
    currency: "AED",
    beds: 3,
    baths: 3,
    area: 280,
    photo: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=2560&q=100",
    gallery: [],
    description: "Beautifully maintained 3-bedroom villa in Jumeirah with private pool and garden. Spacious living areas, maids room, covered parking. Walking distance to the beach.",
    features: [{ label: "Pool", value: "Private" }, { label: "Garden", value: "Yes" }, { label: "Beach", value: "600m" }],
    yearBuilt: 2015,
    floor: null,
    totalFloors: 2,
    isPublished: true,
  },
  {
    title: "Downtown Dubai 1-Bed Serviced Apartment",
    location: "Downtown Dubai, Dubai",
    city: "Downtown Dubai",
    region: "dubai",
    type: "apartment" as const,
    status: "rent" as const,
    priceAmount: 9500,
    currency: "AED",
    beds: 1,
    baths: 1,
    area: 72,
    photo: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=2560&q=100",
    gallery: [],
    description: "Stylish 1-bedroom serviced apartment in Downtown Dubai. Hotel-quality furnishings, housekeeping service, gym and pool access. Ideal for executives and short-term stays.",
    features: [{ label: "Housekeeping", value: "Weekly" }, { label: "Fountain View", value: "Partial" }, { label: "Term", value: "Flexible" }],
    yearBuilt: 2020,
    floor: 22,
    totalFloors: 40,
    isPublished: true,
  },
  {
    title: "Dubai Hills 4-Bed Family Villa",
    location: "Dubai Hills Estate, Dubai",
    city: "Dubai Hills",
    region: "dubai",
    type: "villa" as const,
    status: "rent" as const,
    priceAmount: 35000,
    currency: "AED",
    beds: 4,
    baths: 4,
    area: 420,
    photo: "https://images.unsplash.com/photo-1526495124232-a04e1849168c?w=2560&q=100",
    gallery: [],
    description: "Large 4-bedroom villa in Dubai Hills Estate, ideal for families. Private garden, maid's room, double garage, and community access to parks, cycling tracks and a mall.",
    features: [{ label: "Maid's Room", value: "Yes" }, { label: "Garage", value: "2 cars" }, { label: "School", value: "In community" }],
    yearBuilt: 2021,
    floor: null,
    totalFloors: 2,
    isPublished: true,
  },
  {
    title: "Business Bay 2-Bed Canal View Apartment",
    location: "Business Bay, Dubai",
    city: "Business Bay",
    region: "dubai",
    type: "apartment" as const,
    status: "rent" as const,
    priceAmount: 11000,
    currency: "AED",
    beds: 2,
    baths: 2,
    area: 108,
    photo: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1600&q=80",
    gallery: [],
    description: "Modern 2-bedroom apartment in Business Bay with direct canal views. Unfurnished, open-plan layout, built-in wardrobes, gym and pool included in rent.",
    features: [{ label: "Canal View", value: "Yes" }, { label: "Furnished", value: "Unfurnished" }, { label: "Metro", value: "8 min walk" }],
    yearBuilt: 2022,
    floor: 11,
    totalFloors: 32,
    isPublished: true,
  },
];

async function main() {
  console.log("Seeding Dubai properties...");
  for (const p of DUBAI_PROPERTIES) {
    await db.property.create({ data: p });
    console.log(`  ✓ ${p.title}`);
  }
  console.log(`Done! ${DUBAI_PROPERTIES.length} properties added.`);
}

main()
  .catch(console.error)
  .finally(() => db.$disconnect());
